### ISSUE TITLE
[BE] API 명세 작성

### ISSUE THREAD

**Issue by honeySleepr** [rxdcxdrnine/todo-list#19]
## 🤷‍♂️ Description
REST API를 설계하여 프론트에서 참고할 수 있도록 명세서를 작성한다. 
 

- 어떤 Http method와 URI를 썼을때 어떤 리소스가 반환되는지를 명세한다.

**Comment by rxdcxdrnine** [comment]
아래의 위키 문서에서 작성한 API 명세를 확인하실 수 있습니다.

<https://github.com/rxdcxdrnine/todo-list/wiki/REST-API-%EB%AA%85%EC%84%B8>
